### PR TITLE
updated starterkit

### PR DESCRIPTION
**Pull request by eTorAken**
- updated to last es6-starterkit
- fixes lints
- removed unused dependencies

### CODE REVIEW

**Comment by elierotenberg** [comment]
Running the code (`gulp && node dist/test`) throws with `Error: only one instance of babel/polyfill is allowed`.

**Comment by eTorAken** [comment]
I think that is due to `immutable-request` which uses an old version of `babel`. I'll work on it.

**Comment by eTorAken** [comment]
[This P/R](https://github.com/elierotenberg/immutable-request/pull/1) might do the work, waiting for its approbation.

**Comment by elierotenberg** [comment]
See https://github.com/elierotenberg/immutable-request/commit/889dfacef82397493a7c8165391f8daf49fca381

**Comment by eTorAken** [comment]
There is still a bug when testing with `node dist/test`. See [elierotenberg/immutable-request/pull/2](https://github.com/elierotenberg/immutable-request/pull/2) for a workaround.

**Pull request merged**
